---
abstract: 'A Perl Module for Generating HTML Navigation Menus'
author:
  - 'Shlomi Fish, E<lt>shlomif@cpan.orgE<gt>, L<http://www.shlomifish.org/> .'
build_requires: {}
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
keywords:
  - arrows
  - bar
  - breadcrumbs
  - css
  - expand
  - hidden
  - html
  - menu
  - menus
  - nav-bar
  - navbar
  - navigation
  - 'navigation aids'
  - nav-menu
  - navmenu
  - next
  - prev
  - previous
  - pure-perl
  - site-map
  - skipped
  - trail
  - tree
  - unexpand
  - up
  - widget
  - widgets
  - xhtml
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Widgets-NavMenu
provides:
  HTML::Widgets::NavMenu:
    file: lib/HTML/Widgets/NavMenu.pm
    version: 1.0603
  HTML::Widgets::NavMenu::Error:
    file: lib/HTML/Widgets/NavMenu.pm
    version: 0
  HTML::Widgets::NavMenu::Error::Redirect:
    file: lib/HTML/Widgets/NavMenu.pm
    version: 0
  HTML::Widgets::NavMenu::EscapeHtml:
    file: lib/HTML/Widgets/NavMenu/EscapeHtml.pm
    version: 0
  HTML::Widgets::NavMenu::ExpandVal:
    file: lib/HTML/Widgets/NavMenu/ExpandVal.pm
    version: 0
  HTML::Widgets::NavMenu::HeaderRole:
    file: lib/HTML/Widgets/NavMenu/HeaderRole.pm
    version: 0
  HTML::Widgets::NavMenu::Iterator::Base:
    file: lib/HTML/Widgets/NavMenu/Iterator/Base.pm
    version: 0
  HTML::Widgets::NavMenu::Iterator::GetCurrentlyActive:
    file: lib/HTML/Widgets/NavMenu.pm
    version: 0
  HTML::Widgets::NavMenu::Iterator::Html:
    file: lib/HTML/Widgets/NavMenu/Iterator/Html.pm
    version: 0
  HTML::Widgets::NavMenu::Iterator::Html::Item:
    file: lib/HTML/Widgets/NavMenu/Iterator/Html.pm
    version: 0
  HTML::Widgets::NavMenu::Iterator::JQTreeView:
    file: lib/HTML/Widgets/NavMenu/Iterator/JQTreeView.pm
    version: 0
  HTML::Widgets::NavMenu::Iterator::NavMenu:
    file: lib/HTML/Widgets/NavMenu/Iterator/NavMenu.pm
    version: 0
  HTML::Widgets::NavMenu::Iterator::NavMenu::HeaderRole:
    file: lib/HTML/Widgets/NavMenu/Iterator/NavMenu/HeaderRole.pm
    version: 0
  HTML::Widgets::NavMenu::Iterator::SiteMap:
    file: lib/HTML/Widgets/NavMenu/Iterator/SiteMap.pm
    version: 0
  HTML::Widgets::NavMenu::JQueryTreeView:
    file: lib/HTML/Widgets/NavMenu/JQueryTreeView.pm
    version: 0
  HTML::Widgets::NavMenu::LeadingPath::Component:
    file: lib/HTML/Widgets/NavMenu.pm
    version: 0
  HTML::Widgets::NavMenu::NodeDescription:
    file: lib/HTML/Widgets/NavMenu.pm
    version: 0
  HTML::Widgets::NavMenu::Object:
    file: lib/HTML/Widgets/NavMenu/Object.pm
    version: 0
  HTML::Widgets::NavMenu::Predicate:
    file: lib/HTML/Widgets/NavMenu/Predicate.pm
    version: 0
  HTML::Widgets::NavMenu::TagGen:
    file: lib/HTML/Widgets/NavMenu/TagGen.pm
    version: 0
  HTML::Widgets::NavMenu::Tree::Iterator:
    file: lib/HTML/Widgets/NavMenu/Tree/Iterator.pm
    version: 0
  HTML::Widgets::NavMenu::Tree::Iterator::Item:
    file: lib/HTML/Widgets/NavMenu/Tree/Iterator/Item.pm
    version: 0
  HTML::Widgets::NavMenu::Tree::Iterator::Stack:
    file: lib/HTML/Widgets/NavMenu/Tree/Iterator/Stack.pm
    version: 0
  HTML::Widgets::NavMenu::Tree::Node:
    file: lib/HTML/Widgets/NavMenu/Tree/Node.pm
    version: 0
  HTML::Widgets::NavMenu::Url:
    file: lib/HTML/Widgets/NavMenu/Url.pm
    version: 0
requires:
  Class::XSAccessor: 0
  IO::Scalar: 0
  Test::More: 0
  perl: v5.6.1
resources:
  homepage: http://web-cpan.shlomifish.org/modules/HTML-Widgets-NavMenu/
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://bitbucket.org/shlomif/perl-html-widgets-navmenu
version: 1.0603
